/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_nn_DLAEngine */

#ifndef _Included_com_intel_analytics_bigdl_nn_DLAEngine
#define _Included_com_intel_analytics_bigdl_nn_DLAEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_nn_DLAEngine
 * Method:    dlaInference
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_analytics_bigdl_nn_DLAEngine_dlaInference
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
